//
// Created by vl0011 on 23. 6. 1.
//

#ifndef P1_GREPFA_MQTT_LIBCONFIG_H
#define P1_GREPFA_MQTT_LIBCONFIG_H

#define GREPFA_MQTT_CONFIGURATION_CERTIFICATION_FROM_ASM


#endif //P1_GREPFA_MQTT_LIBCONFIG_H
