//
// Created by vl0011 on 23. 6. 1.
//

#ifndef P1_NETWORKING_LIBCONFIG_H
#define P1_NETWORKING_LIBCONFIG_H
#include <sdkconfig.h>
#include <esp_wifi_types.h>


// default value
#define NETWORKING_DEFAULT_SCAN_METHOD WIFI_FAST_SCAN
#define NETWORKING_DEFAULT_SORT_METHOD WIFI_CONNECT_AP_BY_SIGNAL
#define NETWORKING_DEFAULT_AUTH_THRESHOLD WIFI_AUTH_OPEN
#define NETWORKING_DEFAULT_RSSI_THRESHOLD (-127)
#define NETWORKING_DEFAULT_PMF false

#define WIFI_NETIF_DESC (char*)"wifi_netif_desc"


// configuration
#define NETWORKING_CONFIGURATION_USE_IPV6 0
#define NETWORKING_CONFIGURATION_SHOW_ERROR_LOG_STR 0


#endif //P1_NETWORKING_LIBCONFIG_H
